# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  # before & init are run at pre-build stage
  - init: |
      echo 'init script'
      yarn install
    # command is run only when gitpod workspace is opening, not on pre-build
    # Should be in command some run:watch or alike
    command: echo 'start script'

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview

